window.OGF_SONGS = [
{
    id: "acting-up",
    title: "ACTING UP",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "4:28",
    genre: "West Coast Hip-Hop",
    collection: "Street Anthems",
    audio: "acting-up.mp3",
    cover: "acting-up-cover.png",
    tagline: "Power isn't given. It's taken.",
    story: "ACTING UP captures the moment confidence replaces doubt. The record reflects pressure, ambition and the decision to take ownership of the path ahead instead of waiting for permission.",
    credits: {
      artist: "OG Famous",
      songwriter: "OG Famous",
      label: "Freak Out Entertainment LLC",
      location: "East Los Angeles / Boyle Heights"
    },
    lyrics: [
      {
        section: "Intro – Menace",
        lines: [
          "Yeah…",
          "West coast pressure, homie…",
          "G-funk in the bloodstream.",
          "OG Famous… Menace…",
          "Freakout Entertainment LLC",
          "Y’all already know what time it is."
        ]
      },
      {
        section: "Hook – OG Famous & Menace",
        lines: [
          "Everybody acting up when the bassline knock,",
          "Chrome on the ride while we circle the block,",
          "West coast livin’, got the whole hood hot,",
          "Talk reckless, get checked right there on the spot.",
          "",
          "Everybody acting up when the old school slap,",
          "Khakis and Chucks with the strap in the back,",
          "OG Famous, Menace bring the pressure like that,",
          "Real west coast music — bring the culture right back."
        ]
      },
      {
        section: "Verse 1 – OG Famous",
        lines: [
          "I’m back on the boulevard, swingin’ through traffic,",
          "Palm trees leanin’ while the beat get tragic,",
          "Low lows hoppin’, hear the trunk go dumb,",
          "Whole block outside when the night time come.",
          "",
          "Raised where the sirens sing lullabies daily,",
          "Where the strong survive and the weak move shaky,",
          "Still got hustle in my bloodline heavy,",
          "Heart cold steel but my mind stay ready.",
          "",
          "Boyle Heights nights taught lessons in pain,",
          "Seen dreams disappear in the gutter and rain,",
          "Now I walk with the weight of the city on mine,",
          "Every scar on my body got a story behind.",
          "",
          "Still move militant, west coast villainous,",
          "OG Famous got the whole room feelin’ this,",
          "Old school flavor with the modern aggression,",
          "Every bar hit hard like a Smith & Wesson.",
          "",
          "Gold Daytons spin while the sunset bleed,",
          "Real ones move silent — suckers stampede,",
          "I ain’t gotta yell for respect on mine,",
          "One look from the squad make the whole room align."
        ]
      },
      {
        section: "Hook – OG Famous & Menace",
        lines: [
          "Everybody acting up when the bassline knock,",
          "Chrome on the ride while we circle the block,",
          "West coast livin’, got the whole hood hot,",
          "Talk reckless, get checked right there on the spot.",
          "",
          "Everybody acting up when the old school slap,",
          "Khakis and Chucks with the strap in the back,",
          "OG Famous, Menace bring the pressure like that,",
          "Real west coast music — bring the culture right back."
        ]
      },
      {
        section: "Verse 2 – Menace",
        lines: [
          "I’m the menace from the avenue, heart black chrome,",
          "Where the gang signs wave and the jackboys roam,",
          "Still posted with the homies near the liquor store light,",
          "Where the bass shake windows every Friday night.",
          "",
          "I spit concrete poetry mixed with aggression,",
          "West side bars with a street corner lesson,",
          "Cube in my spirit, Mack 10 in my walk,",
          "Every sentence got weight every time that I talk.",
          "",
          "Still got smoke for the fake and fraud,",
          "Industry cats soft — we was raised too hard,",
          "Palm trees swayin’ but the streets stay wicked,",
          "One false move and your whole card lifted.",
          "",
          "I came from the era where respect meant survival,",
          "Now everybody tough through a phone and a viral,",
          "But me? I still stand on the code I was taught,",
          "Never fold under pressure when the tension get caught.",
          "",
          "Menace keep the G-funk alive in the veins,",
          "While these new rappers dance, we bring back pain,",
          "Freakout Entertainment got the city on lock,",
          "West coast soldiers till the heartbeat stop."
        ]
      },
      {
        section: "Bridge – OG Famous",
        lines: [
          "Cadillacs glidin’…",
          "Streetlights flashin’…",
          "Old school tapes in the deck still slappin’…",
          "If you know about the west, then you know how we move…",
          "Everything heavy when the G-funk groove…"
        ]
      },
      {
        section: "Verse 3 – OG Famous & Menace",
        lines: [
          "[OG Famous]",
          "We built from the asphalt, forged in the heat,",
          "Learned how to hustle before we learned peace,",
          "Every alley got ghosts, every block got scars,",
          "Still we shoot for the moon from behind prison bars.",
          "",
          "[Menace]",
          "Still throw flames when I touch these tracks,",
          "Turn a whole studio session to a hood relapse,",
          "808 heartbeat with the talkbox glide,",
          "West coast resurrection every time we ride.",
          "",
          "[OG Famous]",
          "I’m a product of the struggle and the city despair,",
          "Made a throne out the pressure and the hatred there,",
          "Now the whole damn movement got the coast on tilt,",
          "Every verse built raw like the houses we built.",
          "",
          "[Menace]",
          "Still too gutter for the mainstream image,",
          "Real street sermons every time that we spit it,",
          "Ain’t no gimmicks in the bloodline here,",
          "Just truth in the booth and the grind all year.",
          "",
          "[Both]",
          "So if the beat hit hard and the crowd turn wild,",
          "That’s that west coast energy raising the dial,",
          "OG Famous and Menace — the real still live,",
          "Bringing back that feeling when the old school ride."
        ]
      },
      {
        section: "Final Hook – Both",
        lines: [
          "Everybody acting up when the bassline knock,",
          "Chrome on the ride while we circle the block,",
          "West coast livin’, got the whole hood hot,",
          "Talk reckless, get checked right there on the spot.",
          "",
          "Everybody acting up when the old school slap,",
          "Khakis and Chucks with the strap in the back,",
          "OG Famous, Menace bring the pressure like that,",
          "Real west coast music — bring the culture right back."
        ]
      },
      {
        section: "Outro – Talking",
        lines: [
          "Yeah…",
          "This for the ones that still ride with the windows down…",
          "Palm trees… low lows… street codes…",
          "OG Famous… Menace…",
          "Freakout Entertainment LLC",
          "West coast forever."
        ]
      }
    ],
    related: ["never-bow", "last-of-the-real-ones", "mob-ties", "chosen-one"],
    available: true
  },
  {
    id: "bad-memories",
    title: "BAD MEMORIES",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Street Reflections",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "barz-go-dumb",
    title: "BARZ GO DUMB",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Street Anthems",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "chosen-one",
    title: "CHOSEN ONE",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Legacy",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "dumb-with-it",
    title: "DUMB WITH IT",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Street Anthems",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "feast-of-the-fallen",
    title: "FEAST OF THE FALLEN",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Dark Chapters",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "im-so-la",
    title: "I'M SO L.A.",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "West Coast",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "fuck-em",
    title: "FUCK 'EM",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Street Anthems",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "ink-on-the-chain",
    title: "INK ON THE CHAIN",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Street Reflections",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "la-summer-nights",
    title: "L.A. SUMMER NIGHTS",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "West Coast",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "lies-severed-them-ties",
    title: "LIES SEVERED THEM TIES",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Street Reflections",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "last-of-the-real-ones",
    title: "LAST OF THE REAL ONES",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Legacy",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "lyrical-warfare",
    title: "LYRICAL WARFARE",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Street Anthems",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "loving-you-from-a-distance",
    title: "LOVING YOU FROM A DISTANCE",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Heart & Soul",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "my-turn-now",
    title: "MY TURN NOW",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Legacy",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "mob-ties",
    title: "MOB TIES",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Street Anthems",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "never-bow",
    title: "NEVER BOW",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Legacy",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "no-comparison",
    title: "NO COMPARISON",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Street Anthems",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "whispers-in-the-wind",
    title: "WHISPERS IN THE WIND",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Heart & Soul",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "who-lied-to-you",
    title: "WHO LIED TO YOU",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Street Reflections",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "when-its-my-time-to-go",
    title: "WHEN IT'S MY TIME TO GO",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Heart & Soul",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "west-coast-book-of-life",
    title: "WEST COAST BOOK OF LIFE",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "West Coast",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "till-the-last-round",
    title: "TILL THE LAST ROUND",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Legacy",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "we-dont-condone-that",
    title: "WE DON'T CONDONE THAT",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "West Coast",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "the-last-regime",
    title: "THE LAST REGIME",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Dark Chapters",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "rhymes-with-reason",
    title: "RHYMES WITH REASON",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Legacy",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  },
  {
    id: "reflections-before-the-grave",
    title: "REFLECTIONS BEFORE THE GRAVE",
    artist: "OG Famous",
    label: "Freak Out Entertainment LLC",
    runtime: "—",
    genre: "West Coast Hip-Hop",
    collection: "Dark Chapters",
    audio: "",
    cover: "",
    tagline: "Coming to the Music Vault.",
    story: "This release is reserved in the OG Famous archive and will unlock when its audio, artwork and official lyrics are added.",
    credits: { artist: "OG Famous", songwriter: "OG Famous", label: "Freak Out Entertainment LLC", location: "East Los Angeles / Boyle Heights" },
    lyrics: [],
    related: [],
    available: false
  }
];
